version: '3'
services:
  web:
    build: ../
    image: test-image
    container_name: test
    ports:
        - 443:443
    volumes:
        - ./app:/var/www/html/



# version: '3'
# services:
#   core-service:
#     build: ../
#     image: test-image
#     container_name: test
#     networks: 
#         - calmeet
#     ports:
#         - 9001:443
#     # external_links:
#     #     - redis
#     #     - mongo
#     volumes:
#         - ./app:/var/www/html/
  
  


# networks:
#   calmeet:   

  # redis:
  #   image: calmeet-backend
  #   container_name: cm-core-microservice
  #   network_mode: cm-network
  #   ports:
  #       - 9001:443
  #   external_links:
  #       - redis
  #       - mongo
  #   volumes:
  #       - ./app:/var/www/html/
  # mongo:
  #   image: docker pull mongo
  #   container_name: cm-core-microservice
  #   network_mode: cm-network
  #   ports:
  #       - 9001:443
  #   external_links:
  #       - redis
  #       - mongo
  #   volumes:
  #       - ./app:/var/www/html/
     
  # bff-service:
  #   build: .
  #   image: calmeet-backend
  #   container_name: cm-bff-microservice
  #   network_mode: cm-network
  #   ports:
  #       - 9002:443
  #   external_links:
  #       - redis
  #       - cm-bff-microservice
  #   volumes:
  #       - ./app:/
  # api-service:
  #   build: .
  #   image: calmeet-backend
  #   container_name: cm-api-microservice
  #   network_mode: cm-network
  #   ports:
  #       - 9003:443
  #   external_links:
  #       - redis
  #       - cm-bff-microservice
  #   volumes:
  #       - ./app:/