version: '3'
services:
  webapp:
    container_name: webapp
    image: openclaps/php7-phalcon
    volumes:
      - ./app:/web-root/app
    ports:
      - 443:443
    environment:
        - HTTPD_APPLICATION_ENV=local
        - HTTPD_LOG_LEVEL=warn
        - PHP_DISPLAY_ERROR=1
        - PHP_DISPLAY_ERROR_REPORTING=-1
        - PHP_TIMEZONE=America/Los_Angeles
        - HTTPD_BASEURL=/
        - HTTPD_SERVER_ADMIN=localhost@localhost.com
        - HTTPD_HOST_NAME=localhost
        #Match with host machine port for proxies to work
        - HTTPD_PORT=443
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./app/data:/data/db
  redis:
    image: redis
    container_name: redis